### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by edherm** [jon-wehner/blueprint#1]
Hello BluePrint team! 

I have reviewed your schema and wanted to leave you some comments. Please look these over, discuss them with your team, and feel free to ask me any questions that you may have.

## Project Table
* This table currently has two foreignKeys, but both relate back to users. You could eliminate the need for the `userId` foreign key by having groups of just 1 for individually owned projects. `groupId`. 
* If you don't want to eliminate this double relationship (maybe you want this relationship to represent an author/owner of a project), then you will need to make sure that a group is made for every project, even if it just has the owner author/owner.

## Task Table
* Why do `status` and `importance` have completely separate tables? It seems like you could simplify your schema by folding those in.
    * Is `status` something other than a boolean? Completed (true) or incomplete (false)? My understanding of Remember the Milk is that this is just a toggle.
    * How are you measuring `importance`? Is this basically a scale (eg: 1 to 10) or a specific selection of string values (eg: `["high", "medium", "low"]`) ? It seems that this could be made with a default value and constraints/validations on your server could ensure it fell within the options you want to restrict the stored value

**Comment by WJVincent** [comment]
We were discussing having an in progress value for the status but I think we decided to just have it be a boolean value and will just add that as a property of the task table. 

The importance table definitely could be folded in as well and just queried from the main table.

Thanks for the feedback!

**Comment by jon-wehner** [comment]
We have decided to simplify the groups feature by associating all users with a group for their solo projects..

**Comment by WJVincent** [comment]
Changes have been implemented.
